import React from 'react'
import GenericHero from '@/components/layout/GenericHero'
import Banner from '@/components/banners/Banner'
import Contacto from '@/components/infoPages/Contacto'

export const metadata = {
  title: "Contacto",
  description: "Generated by create next app",
};

const contact = () => {
  return (
    <div>
        <GenericHero children="CONTÁCTA CON NOSOTROS" imgUrl="contacto"/>
        <Contacto/>

      <Banner/>
    </div>
  )
}

export default contact