import React from 'react'
import Privacity from '@/components/enlacesLegales/Privacity'

export const metadata = {
  title: "Política de privacidad",
  description: "Generated by create next app",
};

const privacity = () => {
  return (
    <div>
        <Privacity/>
    </div>
  )
}

export default privacity