import Cookies from '@/components/enlacesLegales/Cookies'
import React from 'react'

export const metadata = {
  title: "Política de cookies",
  description: "Generated by create next app",
};

const cookies = () => {
  return (
    <div>
        <Cookies/>
    </div>
  )
}

export default cookies