import React from 'react'
import GenericHero from '@/components/layout/GenericHero'
import AlquilerConductor from '@/components/infoPages/AlquilerConductor'

export const metadata = {
  title: "Alquiler con conductor",
  description: "Generated by create next app",
};

const alquiler_con_conductor = () => {
  return (
    <>
        <GenericHero children="ALQUILER CON CONDUCTOR" imgUrl="alquiler"/>
        <AlquilerConductor/>
    </>
  )
}

export default alquiler_con_conductor